name: Generate Snake (Dark Mode)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake-dark.svg
          color_snake: "#39FF14"             # neon green snake
          color_dots: "#1db954,#161b22"      # bright green (active), dark (inactive)
          color_background: "#0d1117"        # GitHub dark background

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
